workflows:
  default:
    name: Build and test Android
    environment:
      vars:
        JAVA_HOME: /data/data/com.termux/files/usr/lib/jvm/java-17-openjdk
    scripts:
      - echo "Starting Android build"
      - ./gradlew build
    artifacts:
      - build/**/outputs/**/*.apk
