workflows:
  default:
    name: Build and test Android
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-1.17.0-openjdk-amd64
    scripts:
      - echo "Starting Android build"
      - ./gradlew build
    artifacts:
      - build/**/outputs/**/*.apk
