workflows:
  default:
    name: Build and test Android
    environment:
      vars:
        JAVA_HOME: /opt/android-sdk-linux/tools/bin
    scripts:
      - echo "Starting Android build"
      - ./gradlew build
    artifacts:
      - build/**/outputs/**/*.apk
